<a href="https://colab.research.google.com/github/joe94113/Machine-Learning/blob/main/pca_selfmade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X = np.array([
          [-1, -1, 3],
          [-2, -1, 4],
          [-3, -2, 5],
          [1, 1, 7]
])
X

array([[-1, -1,  3],
       [-2, -1,  4],
       [-3, -2,  5],
       [ 1,  1,  7]])

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
X_pca

array([[-0.9700604 ,  1.49158925],
       [-1.0424408 ,  0.14598684],
       [-1.61347542, -1.43849526],
       [ 3.62597662, -0.19908083]])

In [ ]:
# 新的正交座標軸
pca.components_

array([[ 0.64804169,  0.49865423,  0.57566129],
       [ 0.53566336,  0.23887969, -0.80993905]])

In [ ]:
newX = X-X.mean(axis=0) #　０是行1是橫
COV = np.cov(newX.T) # 協方差，T = 反轉
COV

array([[2.91666667, 2.08333333, 1.58333333],
       [2.08333333, 1.58333333, 1.41666667],
       [1.58333333, 1.41666667, 2.91666667]])

In [ ]:
from numpy import linalg as LA
W, V = LA.eig(COV) # 計算矩陣的特徵值個特徵向量
Q_T, A, Q = V, np.diag(W), V.T

In [ ]:
Q_T.dot(A).dot(Q) # 點積

array([[2.91666667, 2.08333333, 1.58333333],
       [2.08333333, 1.58333333, 1.41666667],
       [1.58333333, 1.41666667, 2.91666667]])

In [ ]:
wq_pair = sorted(zip(W, Q), key=lambda x:x[0], reverse=True)
Q_fil = np.array([v for w,v in wq_pair[:2]])
Q_fil

array([[-0.64804169, -0.49865423, -0.57566129],
       [-0.53566336, -0.23887969,  0.80993905]])

In [ ]:
Q_fil.dot(newX.T).T

array([[ 0.9700604 , -1.49158925],
       [ 1.0424408 , -0.14598684],
       [ 1.61347542,  1.43849526],
       [-3.62597662,  0.19908083]])

In [ ]:
X_pca

array([[-0.9700604 ,  1.49158925],
       [-1.0424408 ,  0.14598684],
       [-1.61347542, -1.43849526],
       [ 3.62597662, -0.19908083]])